version: '3.8'

services:
  web:
    build: .
    container_name: noted_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: noted_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: noted_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
